### ISSUE TITLE
new release for unreleased changes

### ISSUE THREAD

**Issue by Segaja** [six-ddc/hss#17]
Hey there. Can we get a new release of hss? If i compare the latest tag to the master ( https://github.com/six-ddc/hss/compare/v1.8...master ) i see some changes which haven't been released yet. I'm especially looking for the release of https://github.com/six-ddc/hss/pull/13 as this is needed to build a proper package for archlinux https://aur.archlinux.org/packages/hss/ .

I would like to remove the need to apply this patch by hand.

**Comment by six-ddc** [comment]
[1.9](https://github.com/six-ddc/hss/releases/tag/1.9) released.
